Pubsub
ONSdigital/ras-rm-mock-eq pull request #14
Opened 2021-11-17 11:57 UTC by arroyoAle

# What and why?
Setting up PubSub connection to complete survey
# How to test?

# Trello

2021-11-17 12:04 UTC, arroyoAle commented
/deploy arroya

2021-11-17 14:20 UTC, arroyoAle commented
/deploy arroya

2021-11-17 14:28 UTC, arroyoAle commented
/deploy arroya

2021-11-17 15:23 UTC, arroyoAle commented
/deploy arroya

2021-11-17 16:39 UTC, arroyoAle commented
/deploy arroya

2021-11-18 13:19 UTC, arroyoAle commented
/deploy arroya

2021-11-22 15:59 UTC, insacuri commented on Pipfile
> +google-cloud-pubsub = "==1.7.0"
Can you try and use * instead.  For most of our repos we do and it works so it should *hopefully* work here

2021-11-22 16:11 UTC, insacuri requested changes
A few small changes but it's looking good.  I'll deploy it to my environment tomorrow to play with it a bit, but it shouldn't take too much more effort to get this in!

2021-11-22 16:11 UTC, insacuri commented on mock_eq/routes.py
> +if Path("git_info").exists():
Can you get rid of this git_info stuff?  It's always been fairly pointless in our other repos so no need to duplicate it here

2021-11-22 16:11 UTC, insacuri commented on git_info
> +{"test": "test"}
Can you delete this file?  It's not really useful in other repos so no need to duplicate it here.

2021-11-22 16:11 UTC, insacuri commented on mock_eq/templates/layouts/_base.html
> +    {% if availability_message %}
You can remove this availability message stuff (Lines 27 to 34).  That's for something specific to frontstage that isn't in this repo

2021-11-22 16:11 UTC, insacuri commented on _infra/helm/mock-eq/templates/deployment.yaml
> -      # readinessProbe:
I think this stuff is actually needed to let k8s know how to ask the app if it's healthy/ready.  Can you add this stuff back?  In theory it should just work as it's very similar to others

Can you also add a very simple /info endpoint to this repo.  Just something that returns something like:
```python
{"status": "healthy"}
```
or something basic like that.

2021-11-23 10:17 UTC, insacuri commented on mock_eq/routes.py
> +    return make_response(jsonify(info), 200)
This can be simplified to 
```python
return jsonify(info)
```

2021-11-23 10:47 UTC, insacuri commented
/deploy manna

2021-11-23 11:10 UTC, insacuri commented
/deploy manna

2021-11-23 13:37 UTC, warrenbailey commented
/deploy baileyw

2021-11-23 14:28 UTC, insacuri commented on config.py
> +    VERSION = "1.0.9"
This isn't needed.  I don't think anything uses this

2021-11-23 14:45 UTC, insacuri approved these changes

2021-11-23 14:55 UTC, warrenbailey approved these changes

2021-11-23 15:05 UTC, merged