update dependencies
ONSdigital/ras-rm-mock-eq pull request #41
Opened 2024-10-04 09:43 UTC by anwilkie

# What and why?
This PR resolves a bunch of dependabot alerts by upgrading dependencies.

# How to test?
Do a `pipenv install`, then  `pipenv graph`, and check that the following dependency versions have been installed:

- setuptools (>=70.0.0)
- werkzeug (>=3.0.3)
- gunicorn (>=22.0.0)
- cryptoography (>=43.0.1)
- urllib3 (>=2.2.2)
- requests (>=2.32.0)
- jinja2 (>=3.1.4)
- idna (>=3.7)
- black (>=24.3.0)
- certifii (>=2024.07.04)

# Jira
[Card](https://jira.ons.gov.uk/browse/RAS-1304)

2024-10-04 10:33 UTC, matthew-robinson-ons commented on Pipfile
> +setuptools = "*"
idna and setuptools are subpackages of google-cloud-pubsub, don't think we want to explicitly declare them in the pipfile.

2024-10-04 10:34 UTC, matthew-robinson-ons requested changes
Versions look fine just not sure we want to be declaring subpackages in the pipfile.

2024-10-07 14:15 UTC, anwilkie commented
/deploy wilkia

2024-10-08 08:40 UTC, matthew-robinson-ons approved these changes
Happy with these changes

2024-10-10 06:19 UTC, pricem14pc commented
/deploy pricem

2024-10-10 07:09 UTC, pricem14pc approved these changes
All bumps surpass the security alert advisables, and successfully tested launching Mock EQ

2024-10-11 08:58 UTC, merged